# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6d68f25c73d359c43eba8b99d0eaef8ca8fc93d158d06f429af19115b4a33e920ebe0199ef6b0448a2b6d80f34ad6483363d7082af63be94bdba3555dae239

test:
  secret_key_base: a1fc4f77f1925d71b94c02f212c41d1ae0c685b643932aed440cb7361d8ef3882359fd6b348b23d7eae4e32c15a7eaacedbbc89797120a14419ce3b3566a3567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
